### ISSUE TITLE
Segfaults using the conda package version hamtv0.3--h5b5514e_1

### ISSUE THREAD

**Issue by TomHarrop** [xfengnefx/hifiasm-meta#24]
Hi,

I've been wrapping `hifiasm_meta` to install it on Galaxy and I've come across three reproducible segfaults using the biocontainer, which is built from the conda package.

I've uploaded the test data I'm using [here](https://github.com/xfengnefx/hifiasm-meta/files/10451890/zymoD6331std-ecoli-ten-percent.42.1.fq.gz).

Thanks!

### 1. The `--force-rs` parameter 

Running this command causes a segfault:

```bash
singularity exec \
	docker://quay.io/biocontainers/hifiasm_meta:hamtv0.3--h5b5514e_1 \
	hifiasm_meta \
	--force-rs \
	-o asm \
	zymoD6331std-ecoli-ten-percent.42.1.fq.gz
```

<details><summary>Click for log</summary>
<p>

```bash
[M::CommandLine_process] Forced pre-ovec read selection. Ignoring count of ovlp.
[M::main] Start: Thu Jan 19 10:03:55 2023

[prof::yak_count] step 1 total 0.02 s, step2 0.06 s, step3 0.25 s.
[M::ha_analyze_count] lowest: count[16383] = 0
[prof::hamt_mark] step1 total 0.02 s, step2 0.14 s
[M::hamt_flt_withsorting] Reads sorted. 
[M::hamt_assemble] read kmer stats collected.
[prof::yak_count] step 1 total 0.03 s, step2 0.06 s, step3 0.24 s.
[M::ha_analyze_count] lowest: count[16383] = 0
[M::hamt_ft_gen::7.527*1.01@16.046GB] ==> filtered out 0 k-mers occurring 1500 or more times
[M::hamt_assemble] generated flt tab.
[M::hamt_pre_ovec_v2] Entered pre-ovec read selection.
[M::ha_pt_gen] counting - minimzers
[prof::yak_count] step 1 total 0.00 s, step2 0.08 s, step3 0.00 s.
[M::ha_pt_gen::7.616*1.01] ==> counted 58537 distinct minimizer k-mers
[M::ha_pt_gen] count[16383] = 0 (for sanity check)
[M::ha_analyze_count] lowest: count[16383] = 0
[M::ha_pt_gen] counting - minimzer positions
[prof::yak_count] step 1 total 0.00 s, step2 0.08 s, step3 0.00 s.
[debug::ha_pt_gen] tot_cnt is 21999, pt->tot_pos is 21999
[M::ha_pt_gen::7.709*1.01] ==> indexed 21999 positions
[prof::hamt_pre_ovec_v2] start ~ done ha_idx: 0.18 s
[M::hamt_pre_ovec_v2] 0 reads with more than desired targets(150). (Total reads: 241)
[prof::hamt_pre_ovec_v2] ha_idx ~ done estimation: 0.09 s
[M::hamt_pre_ovec_v2] Ignore estimated total number of overlaps and proceed to read selection.
[M::hamt_pre_ovec_v2] plan to keep 161 out of 241 reads (66.80%).
[M::hamt_flt_withsorting_supervised] entering round#2, pass#0...
[W::worker_process_one_read_inclusive2] read limit reached in round#2.
[prof::hamt_flt_withsorting_supervised] step1 0.10 s, step2 0.06 s, step3 0.14 s
[prof::hamt_flt_withsorting_supervised] used 0.24 s
[M::hamt_flt_withsorting_supervised] finished selection, retained 162 reads (goal was 161; total read count is 241).
[prof::hamt_pre_ovec_v2]     ~ done supervised: 0.24 s
[M::hamt_pre_ovec_v2] finished read selection, took 0.51s.
[M::hamt_assemble] read selection dropped reads, recalculate ha_flt_tab...
[prof::yak_count] step 1 total 0.00 s, step2 0.05 s, step3 0.18 s.
[M::ha_analyze_count] lowest: count[16383] = 0
[M::hamt_ft_gen::9.574*1.01@16.467GB] ==> filtered out 0 k-mers occurring 1500 or more times
[M::hamt_assemble] finished redo ha_flt_tab.


[M::hamt_assemble] entered read correction round 1
[M::ha_pt_gen] counting - minimzers
[prof::yak_count] step 1 total 0.00 s, step2 0.08 s, step3 0.00 s.
[M::ha_pt_gen::9.665*1.01] ==> counted 58537 distinct minimizer k-mers
[M::ha_pt_gen] count[16383] = 0 (for sanity check)
[M::ha_analyze_count] lowest: count[16383] = 0
[M::ha_pt_gen] counting - minimzer positions
[prof::yak_count] step 1 total 0.00 s, step2 0.08 s, step3 0.00 s.
[debug::ha_pt_gen] tot_cnt is 21999, pt->tot_pos is 21999
[M::ha_pt_gen::9.757*1.01] ==> indexed 21999 positions
[M::hamt_assemble::9.842*1.01@16.467GB] ==> corrected reads for round 1
[M::hamt_assemble] # bases: 1696054; # corrected bases: 8; # recorrected bases: 0
[M::hamt_assemble] size of buffer: 0.007GB
[probe::hamt_assemble] used 0.27 s


[M::hamt_assemble] entered read correction round 2
[M::ha_pt_gen] counting - minimzers
[prof::yak_count] step 1 total 0.00 s, step2 0.08 s, step3 0.00 s.
[M::ha_pt_gen::9.933*1.01] ==> counted 58533 distinct minimizer k-mers
[M::ha_pt_gen] count[16383] = 0 (for sanity check)
[M::ha_analyze_count] lowest: count[16383] = 0
[M::ha_pt_gen] counting - minimzer positions
[prof::yak_count] step 1 total 0.00 s, step2 0.09 s, step3 0.00 s.
[debug::ha_pt_gen] tot_cnt is 22004, pt->tot_pos is 22004
[M::ha_pt_gen::10.027*1.01] ==> indexed 22004 positions
[M::hamt_assemble::10.111*1.01@16.467GB] ==> corrected reads for round 2
[M::hamt_assemble] # bases: 1696052; # corrected bases: 0; # recorrected bases: 0
[M::hamt_assemble] size of buffer: 0.007GB
[probe::hamt_assemble] used 0.27 s


[M::hamt_assemble] entered read correction round 3
[M::ha_pt_gen] counting - minimzers
[prof::yak_count] step 1 total 0.00 s, step2 0.08 s, step3 0.00 s.
[M::ha_pt_gen::10.201*1.01] ==> counted 58533 distinct minimizer k-mers
[M::ha_pt_gen] count[16383] = 0 (for sanity check)
[M::ha_analyze_count] lowest: count[16383] = 0
[M::ha_pt_gen] counting - minimzer positions
[prof::yak_count] step 1 total 0.00 s, step2 0.09 s, step3 0.00 s.
[debug::ha_pt_gen] tot_cnt is 22004, pt->tot_pos is 22004
[M::ha_pt_gen::10.295*1.01] ==> indexed 22004 positions
[M::hamt_assemble::10.377*1.01@16.467GB] ==> corrected reads for round 3
[M::hamt_assemble] # bases: 1696052; # corrected bases: 0; # recorrected bases: 0
[M::hamt_assemble] size of buffer: 0.007GB
[probe::hamt_assemble] used 0.27 s
[M::ha_pt_gen] counting - minimzers
[prof::yak_count] step 1 total 0.00 s, step2 0.08 s, step3 0.00 s.
[M::ha_pt_gen::10.467*1.01] ==> counted 58533 distinct minimizer k-mers
[M::ha_pt_gen] count[16383] = 0 (for sanity check)
[M::ha_analyze_count] lowest: count[16383] = 0
[M::ha_pt_gen] counting - minimzer positions
[prof::yak_count] step 1 total 0.00 s, step2 0.09 s, step3 0.00 s.
[debug::ha_pt_gen] tot_cnt is 22004, pt->tot_pos is 22004
[M::ha_pt_gen::10.560*1.01] ==> indexed 22004 positions
[M::hamt_assemble::10.622*1.01@16.467GB] ==> found overlaps for the final round
[probe::hamt_assemble] used 0.25 s
[M::ha_print_ovlp_stat] # overlaps: 57
[M::ha_print_ovlp_stat] # strong overlaps: 0
[M::ha_print_ovlp_stat] # weak overlaps: 57
[M::ha_print_ovlp_stat] # exact overlaps: 5
[M::ha_print_ovlp_stat] # inexact overlaps: 52
[M::ha_print_ovlp_stat] # overlaps without large indels: 57
[M::ha_print_ovlp_stat] # reverse overlaps: 0
[M::hist_readlength] <  1.0k: 0
[M::hist_readlength] 1.0k: 0
[M::hist_readlength] 1.5k: 0
[M::hist_readlength] 2.0k: 0
[M::hist_readlength] 2.5k: 0
[M::hist_readlength] 3.0k: ] 3
[M::hist_readlength] 3.5k: ] 6
[M::hist_readlength] 4.0k: ] 3
[M::hist_readlength] 4.5k: ] 13
[M::hist_readlength] 5.0k: ] 5
[M::hist_readlength] 5.5k: ] 15
[M::hist_readlength] 6.0k: ] 13
[M::hist_readlength] 6.5k: ] 8
[M::hist_readlength] 7.0k: ] 14
[M::hist_readlength] 7.5k: ] 12
[M::hist_readlength] 8.0k: ] 11
[M::hist_readlength] 8.5k: ] 7
[M::hist_readlength] 9.0k: ] 8
[M::hist_readlength] 9.5k: ] 10
[M::hist_readlength] 10.0k: ] 8
[M::hist_readlength] 10.5k: ] 9
[M::hist_readlength] 11.0k: ] 12
[M::hist_readlength] 11.5k: ] 6
[M::hist_readlength] 12.0k: ] 6
[M::hist_readlength] 12.5k: ] 9
[M::hist_readlength] 13.0k: ] 5
[M::hist_readlength] 13.5k: ] 5
[M::hist_readlength] 14.0k: ] 6
[M::hist_readlength] 14.5k: ] 5
[M::hist_readlength] 15.0k: ] 4
[M::hist_readlength] 15.5k: ] 6
[M::hist_readlength] 16.0k: ] 4
[M::hist_readlength] 16.5k: ] 4
[M::hist_readlength] 17.0k: ] 1
[M::hist_readlength] 17.5k: ] 3
[M::hist_readlength] 18.0k: ] 2
[M::hist_readlength] 18.5k: ] 3
[M::hist_readlength] 19.0k: ] 1
[M::hist_readlength] 19.5k: ] 3
[M::hist_readlength] 20.0k: ] 1
[M::hist_readlength] 20.5k: 0
[M::hist_readlength] 21.0k: ] 2
[M::hist_readlength] 21.5k: ] 1
[M::hist_readlength] 22.0k: ] 5
[M::hist_readlength] 22.5k: ] 1
[M::hist_readlength] 23.0k: 0
[M::hist_readlength] 23.5k: 0
[M::hist_readlength] 24.0k: 0
[M::hist_readlength] 24.5k: 0
[M::hist_readlength] 25.0k: 0
[M::hist_readlength] 25.5k: 0
[M::hist_readlength] 26.0k: 0
[M::hist_readlength] 26.5k: 0
[M::hist_readlength] 27.0k: ] 1
[M::hist_readlength] >50.0k: 0
Writing reads to disk... 
wrote cmd of length 245: hamt version=0.2-r058, ha base version=0.13-r308, CMD= /usr/local/bin/hifiasm_meta --force-rs -o asm zymoD6331std-ecoli-ten-percent.42.1.fq.gz
Bin file was created on Thu Jan 19 10:04:06 2023
Hifiasm_meta 0.2-r058 (hifiasm code base 0.13-r308).
Reads has been written.
[hamt::write_All_reads] Writing per-read coverage info...
[hamt::write_All_reads] Finished writing.
Writing ma_hit_ts to disk... 
ma_hit_ts has been written.
Writing ma_hit_ts to disk... 
ma_hit_ts has been written.
bin files have been written.
[M::hamt_clean_graph] no debug gfa
[debug::hamt_normalize_ma_hit_t_single_side_advance] nb_batch: 4
[M::hamt_normalize_ma_hit_t_single_side_advance] takes 0.00s, typeA 17 B 39

[debug::hamt_normalize_ma_hit_t_single_side_advance] nb_batch: 4
[M::hamt_normalize_ma_hit_t_single_side_advance] takes 0.00s, typeA 0 B 0

[M::clean_weak_ma_hit_t] takes 0.00 s, treated 0

[debug::ma_hit_contained_advance] ret0: 1, used 0.00 s
[M::ma_hit_contained_advance] dropped 225 reads, used total of 0.00 s

Writing raw unitig GFA to disk... 
[M::hamt_ug_pop_simpleInvertBubble] popped 0 locations
[M::hamt_ug_oneutgCircleCut] treated 0 spots
[M::hamt_output_unitig_graph_advance] Writing GFA... 
[M::hamt_ug_drop_shorter_ovlp] cut 0
[M::hamt_asgarc_ugCovCutDFSCircle_aggressive] cut 0.
[M::hamt_ug_oneutgCircleCut] treated 0 spots
[M::hamt_ug_basic_topoclean_simple] total cut: 0
Segmentation fault (core dumped)

```

</p>
</details>

### 2. Trying to write to an output directory that doesn't exist

Running this command causes a segfault:

```bash
ls -lh . &&
singularity exec \
	docker://quay.io/biocontainers/hifiasm_meta:hamtv0.3--h5b5514e_1 \
	hifiasm_meta \
	-o somedir/asm \
	zymoD6331std-ecoli-ten-percent.42.1.fq.gz
```
<details><summary>Click for log</summary>
<p>

```bash
-rw-rw-r-- 1 tom tom 912K Jan 19 09:54 zymoD6331std-ecoli-ten-percent.42.1.fq.gz
INFO:    Using cached SIF image
[M::main] Start: Thu Jan 19 10:06:12 2023

[M::hamt_assemble] Skipped read selection.
[prof::yak_count] step 1 total 0.02 s, step2 0.06 s, step3 0.23 s.
[M::ha_analyze_count] lowest: count[16383] = 0
[M::hamt_ft_gen::3.800*1.01@16.046GB] ==> filtered out 0 k-mers occurring 750 or more times
[M::hamt_assemble] Generated flt tab.


[M::hamt_assemble] entered read correction round 1
[M::ha_pt_gen] counting - minimzers
[prof::yak_count] step 1 total 0.03 s, step2 0.08 s, step3 0.00 s.
[M::ha_pt_gen::3.919*1.01] ==> counted 58537 distinct minimizer k-mers
[M::ha_pt_gen] count[16383] = 0 (for sanity check)
[M::ha_analyze_count] lowest: count[16383] = 0
[M::ha_pt_gen] counting - minimzer positions
[prof::yak_count] step 1 total 0.00 s, step2 0.08 s, step3 0.00 s.
[debug::ha_pt_gen] tot_cnt is 21999, pt->tot_pos is 21999
[M::ha_pt_gen::4.010*1.01] ==> indexed 21999 positions
[M::hamt_assemble::4.184*1.01@16.046GB] ==> corrected reads for round 1
[M::hamt_assemble] # bases: 2515730; # corrected bases: 27; # recorrected bases: 0
[M::hamt_assemble] size of buffer: 0.007GB
[probe::hamt_assemble] used 0.38 s


[M::hamt_assemble] entered read correction round 2
[M::ha_pt_gen] counting - minimzers
[prof::yak_count] step 1 total 0.00 s, step2 0.08 s, step3 0.00 s.
[M::ha_pt_gen::4.270*1.01] ==> counted 58533 distinct minimizer k-mers
[M::ha_pt_gen] count[16383] = 0 (for sanity check)
[M::ha_analyze_count] lowest: count[16383] = 0
[M::ha_pt_gen] counting - minimzer positions
[prof::yak_count] step 1 total 0.00 s, step2 0.08 s, step3 0.00 s.
[debug::ha_pt_gen] tot_cnt is 22004, pt->tot_pos is 22004
[M::ha_pt_gen::4.361*1.01] ==> indexed 22004 positions
[M::hamt_assemble::4.530*1.01@16.046GB] ==> corrected reads for round 2
[M::hamt_assemble] # bases: 2515713; # corrected bases: 2; # recorrected bases: 0
[M::hamt_assemble] size of buffer: 0.007GB
[probe::hamt_assemble] used 0.35 s


[M::hamt_assemble] entered read correction round 3
[M::ha_pt_gen] counting - minimzers
[prof::yak_count] step 1 total 0.00 s, step2 0.08 s, step3 0.00 s.
[M::ha_pt_gen::4.617*1.01] ==> counted 58533 distinct minimizer k-mers
[M::ha_pt_gen] count[16383] = 0 (for sanity check)
[M::ha_analyze_count] lowest: count[16383] = 0
[M::ha_pt_gen] counting - minimzer positions
[prof::yak_count] step 1 total 0.00 s, step2 0.08 s, step3 0.00 s.
[debug::ha_pt_gen] tot_cnt is 22004, pt->tot_pos is 22004
[M::ha_pt_gen::4.707*1.01] ==> indexed 22004 positions
[M::hamt_assemble::4.875*1.01@16.046GB] ==> corrected reads for round 3
[M::hamt_assemble] # bases: 2515713; # corrected bases: 0; # recorrected bases: 0
[M::hamt_assemble] size of buffer: 0.007GB
[probe::hamt_assemble] used 0.34 s
[M::ha_pt_gen] counting - minimzers
[prof::yak_count] step 1 total 0.00 s, step2 0.08 s, step3 0.00 s.
[M::ha_pt_gen::4.961*1.01] ==> counted 58533 distinct minimizer k-mers
[M::ha_pt_gen] count[16383] = 0 (for sanity check)
[M::ha_analyze_count] lowest: count[16383] = 0
[M::ha_pt_gen] counting - minimzer positions
[prof::yak_count] step 1 total 0.00 s, step2 0.08 s, step3 0.00 s.
[debug::ha_pt_gen] tot_cnt is 22004, pt->tot_pos is 22004
[M::ha_pt_gen::5.051*1.01] ==> indexed 22004 positions
Segmentation fault (core dumped)
```

</p>
</details>

This works fine:

```bash
mkdir somedir &&
singularity exec \
	docker://quay.io/biocontainers/hifiasm_meta:hamtv0.3--h5b5514e_1 \
	hifiasm_meta \
	-o somedir/asm \
	zymoD6331std-ecoli-ten-percent.42.1.fq.gz
```

### 3. Running `hifiasm_meta --help`, or another parameter that doesn't exist

```bash
singularity exec \
	docker://quay.io/biocontainers/hifiasm_meta:hamtv0.3--h5b5514e_1 \
	hifiasm_meta --help

[ERROR] unknown option in "--help"
[M::main] Start: Thu Jan 19 10:08:51 2023

[M::hamt_assemble] Skipped read selection.
Segmentation fault (core dumped)

singularity exec \
	docker://quay.io/biocontainers/hifiasm_meta:hamtv0.3--h5b5514e_1 \
	hifiasm_meta --someparam

[ERROR] unknown option in "--someparam"
[M::main] Start: Thu Jan 19 10:09:34 2023

[M::hamt_assemble] Skipped read selection.
Segmentation fault (core dumped)


```

### `hifiasm_meta --version` doesn't exit cleanly (not a segfault)

I get an exit code of `1` for this.

```bash
singularity exec \
	docker://quay.io/biocontainers/hifiasm_meta:hamtv0.3--h5b5514e_1 \
	hifiasm_meta --version ;
echo $?

ha base version: 0.13-r308
hamt version: 0.2-r058
1
```

**Comment by xfengnefx** [comment]
I think --version exits with 1 because a successful run expects an assembly, not the command not crushing. For your workflow, do you need the return value to be different from errors? Maybe I can set it to be 2?

Issue 1 and 2 seem to have been fixed in the latest commit, and 3 is fixed locally. I can push and update conda once you decide the above.

**Comment by TomHarrop** [comment]
Thanks for the quick fixes! Once you've updated the conda version I will add it to Galaxy.

I don't have a preference for the return code of  `--version`.  I mentioned it because I would usually expect it to print the version and exit cleanly. For example, if I did something like `hifiasm_meta --version &>> log.txt` in a workflow, I wouldn't expect that to return an error. If you are using e.g. bash in strict mode, that would stop the workflow.

**Comment by xfengnefx** [comment]
I made -h and --version to return 0. Along with the other updates they are pushed to `meta` branch, and waiting for bioconda [pr](https://github.com/bioconda/bioconda-recipes/pull/39031). Will ping once it's done.

**Comment by TomHarrop** [comment]
I am still getting a segfault for the first command.

```bash
singularity exec    \
	docker://quay.io/biocontainers/hifiasm_meta:hamtv0.3.1--h5b5514e_0 \
	hifiasm_meta \
	--force-rs \
	-o asm \
	zymoD6331std-ecoli-ten-percent.42.1.fq.gz
```

<details><summary>Click for log</summary>
<p>

```
[M::CommandLine_process] Forced pre-ovec read selection. Ignoring count of ovlp.
[M::main] Start: Tue Jan 31 15:44:31 2023

Reads has been loaded. Bin file info: hamt version=0.2-r058, ha base version=0.13-r308, CMD= /usr/local/bin/hifiasm_meta --force-rs -o asm zymoD6331std-ecoli-ten-percent.42.1.fq.gz
Bin file was created on Tue Jan 31 15:37:37 2023
Hifiasm_meta 0.2-r058 (hifiasm code base 0.13-r308).

Loading hamt bin...
Loaded hamt bin.
[M::hamt_ovecinfo_load_from_disk] try loading ovecinfo bin file
[M::hamt_ovecinfo_load_from_disk] loaded; used 0.0 s

Loading ma_hit_ts from disk (asm.ovlp.source)... 
ma_hit_ts has been read (time: 0.00 s).
Loading ma_hit_ts from disk (asm.ovlp.reverse)... 
ma_hit_ts has been read (time: 0.00 s).
[M::load_all_data_from_disk] loaded; used 0.00 s
[M::hamt_assemble::0.002*15.83] ==> loaded corrected reads and overlaps from disk
[M::hist_readlength] <  1.0k: 0
[M::hist_readlength] 1.0k: 0
[M::hist_readlength] 1.5k: 0
[M::hist_readlength] 2.0k: 0
[M::hist_readlength] 2.5k: 0
[M::hist_readlength] 3.0k: ] 3
[M::hist_readlength] 3.5k: ] 6
[M::hist_readlength] 4.0k: ] 3
[M::hist_readlength] 4.5k: ] 13
[M::hist_readlength] 5.0k: ] 5
[M::hist_readlength] 5.5k: ] 15
[M::hist_readlength] 6.0k: ] 13
[M::hist_readlength] 6.5k: ] 8
[M::hist_readlength] 7.0k: ] 14
[M::hist_readlength] 7.5k: ] 12
[M::hist_readlength] 8.0k: ] 11
[M::hist_readlength] 8.5k: ] 7
[M::hist_readlength] 9.0k: ] 8
[M::hist_readlength] 9.5k: ] 10
[M::hist_readlength] 10.0k: ] 8
[M::hist_readlength] 10.5k: ] 9
[M::hist_readlength] 11.0k: ] 12
[M::hist_readlength] 11.5k: ] 6
[M::hist_readlength] 12.0k: ] 6
[M::hist_readlength] 12.5k: ] 9
[M::hist_readlength] 13.0k: ] 5
[M::hist_readlength] 13.5k: ] 5
[M::hist_readlength] 14.0k: ] 6
[M::hist_readlength] 14.5k: ] 5
[M::hist_readlength] 15.0k: ] 4
[M::hist_readlength] 15.5k: ] 6
[M::hist_readlength] 16.0k: ] 4
[M::hist_readlength] 16.5k: ] 4
[M::hist_readlength] 17.0k: ] 1
[M::hist_readlength] 17.5k: ] 3
[M::hist_readlength] 18.0k: ] 2
[M::hist_readlength] 18.5k: ] 3
[M::hist_readlength] 19.0k: ] 1
[M::hist_readlength] 19.5k: ] 3
[M::hist_readlength] 20.0k: ] 1
[M::hist_readlength] 20.5k: 0
[M::hist_readlength] 21.0k: ] 2
[M::hist_readlength] 21.5k: ] 1
[M::hist_readlength] 22.0k: ] 5
[M::hist_readlength] 22.5k: ] 1
[M::hist_readlength] 23.0k: 0
[M::hist_readlength] 23.5k: 0
[M::hist_readlength] 24.0k: 0
[M::hist_readlength] 24.5k: 0
[M::hist_readlength] 25.0k: 0
[M::hist_readlength] 25.5k: 0
[M::hist_readlength] 26.0k: 0
[M::hist_readlength] 26.5k: 0
[M::hist_readlength] 27.0k: ] 1
[M::hist_readlength] >50.0k: 0
[M::hamt_clean_graph] no debug gfa
[debug::hamt_normalize_ma_hit_t_single_side_advance] nb_batch: 4
[M::hamt_normalize_ma_hit_t_single_side_advance] typeA 17 B 39, used 0.0s

[debug::hamt_normalize_ma_hit_t_single_side_advance] nb_batch: 4
[M::hamt_normalize_ma_hit_t_single_side_advance] typeA 0 B 0, used 0.0s

[M::clean_weak_ma_hit_t] treated 0, used 0.0s
[M::ma_hit_sub] remained 241, deleted 0, used 0.0s
[M::detect_chimeric_reads_conservative] n_simple_remove: 0, n_complex_remove: 0/0, used 0.0
[M::ma_hit_cut] typeA 0 , typeB 223, used 0.0
[M::ma_hit_flt] typeA 0 , typeB 223, used 0.0s
[M::hamt_hit_contained_multi] treated roughly 0 spots, used 0.0s
[M::hamt_hit_contained_drop_singleton_multi] treated roughly 0 spots, used 0.0s
[debug::ma_hit_contained_advance] ret0: 1, used 0.00 s
[M::ma_hit_contained_advance] dropped 225 reads, used total of 0.00 s

[M::asg_arc_del_trans] reduced 0 arcs, used 0.0s
[M::asg_cut_tip] cut 8 tips, used 0.0 s
[M::hamt_clean_graph] ====== initial clean ======


**********0-th round drop: drop_ratio = 0.200000**********
[M::asg_arc_del_simple_circle_untig] removed 0 self-circles, used 0.0s
[M::asg_cut_tip] cut 0 tips, used 0.0 s
[M::hamt_asgarc_drop_tips_and_bubbles] did 0 rounds, dropped 0 spots, used 0.0 s

[M::asg_arc_identify_simple_bubbles_multi] dropped total of 0, used 0.0s
[M::asg_arc_del_false_node_meta] removed 0 single nodes, used 0.0
[M::asg_cut_tip] cut 0 tips, used 0.0 s
[M::asg_arc_identify_simple_bubbles_multi] dropped total of 0, used 0.0s
[M::asg_arc_del_short_diploid_by_exact] removed 0 inexact overlaps, used 0.0s
[M::asg_cut_tip] cut 0 tips, used 0.0 s
[M::asg_arc_identify_simple_bubbles_multi] dropped total of 0, used 0.0s
[M::asg_arc_del_short_diploid_by_length] removed 0 short overlaps, used 0.0
[M::asg_cut_tip] cut 0 tips, used 0.0 s
[M::asg_arc_identify_simple_bubbles_multi] dropped total of 0, used 0.0s
[M::asg_arc_del_short_false_link] removed 0 false overlaps, used 0.0s
[M::asg_arc_identify_simple_bubbles_multi] dropped total of 0, used 0.0s
[M::asg_arc_del_complex_false_link] removed 0 false overlaps, used 0.0s
[M::asg_cut_tip] cut 0 tips, used 0.0 s


**********1-th round drop: drop_ratio = 0.400000**********
[M::asg_arc_del_simple_circle_untig] removed 0 self-circles, used 0.0s
[M::asg_cut_tip] cut 0 tips, used 0.0 s
[M::hamt_asgarc_drop_tips_and_bubbles] did 0 rounds, dropped 0 spots, used 0.0 s

[M::asg_arc_identify_simple_bubbles_multi] dropped total of 0, used 0.0s
[M::asg_arc_del_false_node_meta] removed 0 single nodes, used 0.0
[M::asg_cut_tip] cut 0 tips, used 0.0 s
[M::asg_arc_identify_simple_bubbles_multi] dropped total of 0, used 0.0s
[M::asg_arc_del_short_diploid_by_exact] removed 0 inexact overlaps, used 0.0s
[M::asg_cut_tip] cut 0 tips, used 0.0 s
[M::asg_arc_identify_simple_bubbles_multi] dropped total of 0, used 0.0s
[M::asg_arc_del_short_diploid_by_length] removed 0 short overlaps, used 0.0
[M::asg_cut_tip] cut 0 tips, used 0.0 s
[M::asg_arc_identify_simple_bubbles_multi] dropped total of 0, used 0.0s
[M::asg_arc_del_short_false_link] removed 0 false overlaps, used 0.0s
[M::asg_arc_identify_simple_bubbles_multi] dropped total of 0, used 0.0s
[M::asg_arc_del_complex_false_link] removed 0 false overlaps, used 0.0s
[M::asg_cut_tip] cut 0 tips, used 0.0 s


**********2-th round drop: drop_ratio = 0.600000**********
[M::asg_arc_del_simple_circle_untig] removed 0 self-circles, used 0.0s
[M::asg_cut_tip] cut 0 tips, used 0.0 s
[M::hamt_asgarc_drop_tips_and_bubbles] did 0 rounds, dropped 0 spots, used 0.0 s

[M::asg_arc_identify_simple_bubbles_multi] dropped total of 0, used 0.0s
[M::asg_arc_del_false_node_meta] removed 0 single nodes, used 0.0
[M::asg_cut_tip] cut 0 tips, used 0.0 s
[M::asg_arc_identify_simple_bubbles_multi] dropped total of 0, used 0.0s
[M::asg_arc_del_short_diploid_by_exact] removed 0 inexact overlaps, used 0.0s
[M::asg_cut_tip] cut 0 tips, used 0.0 s
[M::asg_arc_identify_simple_bubbles_multi] dropped total of 0, used 0.0s
[M::asg_arc_del_short_diploid_by_length] removed 0 short overlaps, used 0.0
[M::asg_cut_tip] cut 0 tips, used 0.0 s
[M::asg_arc_identify_simple_bubbles_multi] dropped total of 0, used 0.0s
[M::asg_arc_del_short_false_link] removed 0 false overlaps, used 0.0s
[M::asg_arc_identify_simple_bubbles_multi] dropped total of 0, used 0.0s
[M::asg_arc_del_complex_false_link] removed 0 false overlaps, used 0.0s
[M::asg_cut_tip] cut 0 tips, used 0.0 s


**********3-th round drop: drop_ratio = 0.800000**********
[M::asg_arc_del_simple_circle_untig] removed 0 self-circles, used 0.0s
[M::asg_cut_tip] cut 0 tips, used 0.0 s
[M::hamt_asgarc_drop_tips_and_bubbles] did 0 rounds, dropped 0 spots, used 0.0 s

[M::asg_arc_identify_simple_bubbles_multi] dropped total of 0, used 0.0s
[M::asg_arc_del_false_node_meta] removed 0 single nodes, used 0.0
[M::asg_cut_tip] cut 0 tips, used 0.0 s
[M::asg_arc_identify_simple_bubbles_multi] dropped total of 0, used 0.0s
[M::asg_arc_del_short_diploid_by_exact] removed 0 inexact overlaps, used 0.0s
[M::asg_cut_tip] cut 0 tips, used 0.0 s
[M::asg_arc_identify_simple_bubbles_multi] dropped total of 0, used 0.0s
[M::asg_arc_del_short_diploid_by_length] removed 0 short overlaps, used 0.0
[M::asg_cut_tip] cut 0 tips, used 0.0 s
[M::asg_arc_identify_simple_bubbles_multi] dropped total of 0, used 0.0s
[M::asg_arc_del_short_false_link] removed 0 false overlaps, used 0.0s
[M::asg_arc_identify_simple_bubbles_multi] dropped total of 0, used 0.0s
[M::asg_arc_del_complex_false_link] removed 0 false overlaps, used 0.0s
[M::asg_cut_tip] cut 0 tips, used 0.0 s


********** last round **********
[M::asg_arc_del_simple_circle_untig] removed 0 self-circles, used 0.0s
[M::asg_cut_tip] cut 0 tips, used 0.0 s
[M::hamt_asgarc_drop_tips_and_bubbles] did 0 rounds, dropped 0 spots, used 0.0 s

[M::asg_arc_del_short_diploi_by_suspect_edge] removed 0 suspect overlaps, used 0.0s
[M::asg_cut_tip] cut 0 tips, used 0.0 s
[M::asg_arc_del_triangular_directly] removed 0 triangular overlaps, used 0.0s
[M::asg_arc_identify_simple_bubbles_multi] dropped total of 0, used 0.0s
[M::asg_cut_tip] cut 0 tips, used 0.0 s
[M::asg_arc_identify_simple_bubbles_multi] dropped total of 0, used 0.0s
[M::asg_arc_del_too_short_overlaps] removed 0 short overlaps, used 0.0s
[M::asg_cut_tip] cut 0 tips, used 0.0 s
[M::asg_arc_del_simple_circle_untig] removed 0 self-circles, used 0.0s


********** checkpoint: r_utg **********
Writing raw unitig GFA to disk... 
[M::hamt_clean_graph] ======= preclean =======
[M::hamt_ug_pop_simpleInvertBubble] popped 0 locations
[M::hamt_ug_oneutgCircleCut] treated 0 spots
[M::hamt_clean_graph] round 0, dropped 0, used 0.0s


********** checkpoint: p_utg **********

[M::hamt_output_unitig_graph_advance] Writing GFA... 
[M::hamt_ug_drop_shorter_ovlp] cut 0
[M::hamt_asgarc_ugCovCutDFSCircle_aggressive] cut 0.


[M::hamt_clean_graph] time check #1, 0.0s
[M::hamt_ug_oneutgCircleCut] treated 0 spots
[M::hamt_ug_basic_topoclean_simple] total cut: 0
Segmentation fault (core dumped)
```

</p>	
</details>

**Comment by xfengnefx** [comment]
Could you try removing the bin files (starts with "asm") and rerun? I tried the current release with ASan, but couldn't get the segfault...

**Comment by TomHarrop** [comment]
Sorry, I posted the wrong log. Here's the correct one without the bin files.

Could it be caused by the small amount of input data? I discovered this while I was trying to generate a test dataset ( < 1 MB ) for Galaxy.

Thanks again for your help with this!

```
[M::CommandLine_process] Forced pre-ovec read selection. Ignoring count of ovlp.
[M::main] Start: Wed Feb  1 09:29:36 2023

[prof::yak_count] step 1 total 0.02 s, step2 0.06 s, step3 0.23 s.
[M::ha_analyze_count] lowest: count[16383] = 0
[prof::hamt_mark] step1 total 0.02 s, step2 0.15 s
[M::hamt_flt_withsorting] Reads sorted. 
[M::hamt_assemble] read kmer stats collected.
[prof::yak_count] step 1 total 0.03 s, step2 0.05 s, step3 0.23 s.
[M::ha_analyze_count] lowest: count[16383] = 0
[M::hamt_ft_gen::7.376*1.00@16.046GB] ==> filtered out 0 k-mers occurring 1500 or more times
[M::hamt_assemble] generated flt tab.
[M::hamt_pre_ovec_v2] Entered pre-ovec read selection.
[M::ha_pt_gen] counting - minimzers
[prof::yak_count] step 1 total 0.00 s, step2 0.08 s, step3 0.00 s.
[M::ha_pt_gen::7.461*1.00] ==> counted 58537 distinct minimizer k-mers
[M::ha_pt_gen] count[16383] = 0 (for sanity check)
[M::ha_analyze_count] lowest: count[16383] = 0
[M::ha_pt_gen] counting - minimzer positions
[prof::yak_count] step 1 total 0.00 s, step2 0.08 s, step3 0.00 s.
[debug::ha_pt_gen] tot_cnt is 21999, pt->tot_pos is 21999
[M::ha_pt_gen::7.551*1.00] ==> indexed 21999 positions
[prof::hamt_pre_ovec_v2] start ~ done ha_idx: 0.17 s
[M::hamt_pre_ovec_v2] 0 reads with more than desired targets(150). (Total reads: 241)
[prof::hamt_pre_ovec_v2] ha_idx ~ done estimation: 0.09 s
[M::hamt_pre_ovec_v2] Ignore estimated total number of overlaps and proceed to read selection.
[M::hamt_pre_ovec_v2] plan to keep 161 out of 241 reads (66.80%).
[M::hamt_flt_withsorting_supervised] entering round#2, pass#0...
[W::worker_process_one_read_inclusive2] read limit reached in round#2.
[prof::hamt_flt_withsorting_supervised] step1 0.09 s, step2 0.06 s, step3 0.13 s
[prof::hamt_flt_withsorting_supervised] used 0.23 s
[M::hamt_flt_withsorting_supervised] finished selection, retained 162 reads (goal was 161; total read count is 241).
[prof::hamt_pre_ovec_v2]     ~ done supervised: 0.23 s
[M::hamt_pre_ovec_v2] finished read selection, took 0.49s.
[M::hamt_assemble] read selection dropped reads, recalculate ha_flt_tab...
[prof::yak_count] step 1 total 0.00 s, step2 0.04 s, step3 0.17 s.
[M::ha_analyze_count] lowest: count[16383] = 0
[M::hamt_ft_gen::9.316*1.00@16.472GB] ==> filtered out 0 k-mers occurring 1500 or more times
[M::hamt_assemble] finished redo ha_flt_tab.


[M::hamt_assemble] entered read correction round 1
[M::ha_pt_gen] counting - minimzers
[prof::yak_count] step 1 total 0.00 s, step2 0.08 s, step3 0.00 s.
[M::ha_pt_gen::9.398*1.00] ==> counted 58537 distinct minimizer k-mers
[M::ha_pt_gen] count[16383] = 0 (for sanity check)
[M::ha_analyze_count] lowest: count[16383] = 0
[M::ha_pt_gen] counting - minimzer positions
[prof::yak_count] step 1 total 0.00 s, step2 0.08 s, step3 0.00 s.
[debug::ha_pt_gen] tot_cnt is 21999, pt->tot_pos is 21999
[M::ha_pt_gen::9.483*1.00] ==> indexed 21999 positions
[M::hamt_assemble::9.567*1.00@16.472GB] ==> corrected reads for round 1
[M::hamt_assemble] # bases: 1696054; # corrected bases: 8; # recorrected bases: 0
[M::hamt_assemble] size of buffer: 0.007GB
[probe::hamt_assemble] used 0.25 s


[M::hamt_assemble] entered read correction round 2
[M::ha_pt_gen] counting - minimzers
[prof::yak_count] step 1 total 0.00 s, step2 0.09 s, step3 0.00 s.
[M::ha_pt_gen::9.658*1.00] ==> counted 58533 distinct minimizer k-mers
[M::ha_pt_gen] count[16383] = 0 (for sanity check)
[M::ha_analyze_count] lowest: count[16383] = 0
[M::ha_pt_gen] counting - minimzer positions
[prof::yak_count] step 1 total 0.00 s, step2 0.08 s, step3 0.00 s.
[debug::ha_pt_gen] tot_cnt is 22004, pt->tot_pos is 22004
[M::ha_pt_gen::9.748*1.00] ==> indexed 22004 positions
[M::hamt_assemble::9.833*1.00@16.472GB] ==> corrected reads for round 2
[M::hamt_assemble] # bases: 1696052; # corrected bases: 0; # recorrected bases: 0
[M::hamt_assemble] size of buffer: 0.007GB
[probe::hamt_assemble] used 0.27 s


[M::hamt_assemble] entered read correction round 3
[M::ha_pt_gen] counting - minimzers
[prof::yak_count] step 1 total 0.00 s, step2 0.08 s, step3 0.00 s.
[M::ha_pt_gen::9.923*1.00] ==> counted 58533 distinct minimizer k-mers
[M::ha_pt_gen] count[16383] = 0 (for sanity check)
[M::ha_analyze_count] lowest: count[16383] = 0
[M::ha_pt_gen] counting - minimzer positions
[prof::yak_count] step 1 total 0.00 s, step2 0.08 s, step3 0.00 s.
[debug::ha_pt_gen] tot_cnt is 22004, pt->tot_pos is 22004
[M::ha_pt_gen::10.011*1.00] ==> indexed 22004 positions
[M::hamt_assemble::10.092*1.00@16.472GB] ==> corrected reads for round 3
[M::hamt_assemble] # bases: 1696052; # corrected bases: 0; # recorrected bases: 0
[M::hamt_assemble] size of buffer: 0.007GB
[probe::hamt_assemble] used 0.26 s
[M::ha_pt_gen] counting - minimzers
[prof::yak_count] step 1 total 0.00 s, step2 0.08 s, step3 0.00 s.
[M::ha_pt_gen::10.178*1.00] ==> counted 58533 distinct minimizer k-mers
[M::ha_pt_gen] count[16383] = 0 (for sanity check)
[M::ha_analyze_count] lowest: count[16383] = 0
[M::ha_pt_gen] counting - minimzer positions
[prof::yak_count] step 1 total 0.00 s, step2 0.08 s, step3 0.00 s.
[debug::ha_pt_gen] tot_cnt is 22004, pt->tot_pos is 22004
[M::ha_pt_gen::10.264*1.00] ==> indexed 22004 positions
[M::hamt_assemble::10.325*1.00@16.472GB] ==> found overlaps for the final round
[probe::hamt_assemble] used 0.23 s
[M::ha_print_ovlp_stat] # overlaps: 57
[M::ha_print_ovlp_stat] # strong overlaps: 0
[M::ha_print_ovlp_stat] # weak overlaps: 57
[M::ha_print_ovlp_stat] # exact overlaps: 5
[M::ha_print_ovlp_stat] # inexact overlaps: 52
[M::ha_print_ovlp_stat] # overlaps without large indels: 57
[M::ha_print_ovlp_stat] # reverse overlaps: 0
[M::hist_readlength] <  1.0k: 0
[M::hist_readlength] 1.0k: 0
[M::hist_readlength] 1.5k: 0
[M::hist_readlength] 2.0k: 0
[M::hist_readlength] 2.5k: 0
[M::hist_readlength] 3.0k: ] 3
[M::hist_readlength] 3.5k: ] 6
[M::hist_readlength] 4.0k: ] 3
[M::hist_readlength] 4.5k: ] 13
[M::hist_readlength] 5.0k: ] 5
[M::hist_readlength] 5.5k: ] 15
[M::hist_readlength] 6.0k: ] 13
[M::hist_readlength] 6.5k: ] 8
[M::hist_readlength] 7.0k: ] 14
[M::hist_readlength] 7.5k: ] 12
[M::hist_readlength] 8.0k: ] 11
[M::hist_readlength] 8.5k: ] 7
[M::hist_readlength] 9.0k: ] 8
[M::hist_readlength] 9.5k: ] 10
[M::hist_readlength] 10.0k: ] 8
[M::hist_readlength] 10.5k: ] 9
[M::hist_readlength] 11.0k: ] 12
[M::hist_readlength] 11.5k: ] 6
[M::hist_readlength] 12.0k: ] 6
[M::hist_readlength] 12.5k: ] 9
[M::hist_readlength] 13.0k: ] 5
[M::hist_readlength] 13.5k: ] 5
[M::hist_readlength] 14.0k: ] 6
[M::hist_readlength] 14.5k: ] 5
[M::hist_readlength] 15.0k: ] 4
[M::hist_readlength] 15.5k: ] 6
[M::hist_readlength] 16.0k: ] 4
[M::hist_readlength] 16.5k: ] 4
[M::hist_readlength] 17.0k: ] 1
[M::hist_readlength] 17.5k: ] 3
[M::hist_readlength] 18.0k: ] 2
[M::hist_readlength] 18.5k: ] 3
[M::hist_readlength] 19.0k: ] 1
[M::hist_readlength] 19.5k: ] 3
[M::hist_readlength] 20.0k: ] 1
[M::hist_readlength] 20.5k: 0
[M::hist_readlength] 21.0k: ] 2
[M::hist_readlength] 21.5k: ] 1
[M::hist_readlength] 22.0k: ] 5
[M::hist_readlength] 22.5k: ] 1
[M::hist_readlength] 23.0k: 0
[M::hist_readlength] 23.5k: 0
[M::hist_readlength] 24.0k: 0
[M::hist_readlength] 24.5k: 0
[M::hist_readlength] 25.0k: 0
[M::hist_readlength] 25.5k: 0
[M::hist_readlength] 26.0k: 0
[M::hist_readlength] 26.5k: 0
[M::hist_readlength] 27.0k: ] 1
[M::hist_readlength] >50.0k: 0
Writing reads to disk... 
wrote cmd of length 249: hamt version=0.3-r063.2, ha base version=0.13-r308, CMD= /usr/local/bin/hifiasm_meta --force-rs -o asm zymoD6331std-ecoli-ten-percent.42.1.fq.gz
Bin file was created on Wed Feb  1 09:29:47 2023
Hifiasm_meta 0.3-r063.2 (hifiasm code base 0.13-r308).
Reads has been written.
[hamt::write_All_reads] Writing per-read coverage info...
[hamt::write_All_reads] Finished writing.
Writing ma_hit_ts to disk... 
ma_hit_ts has been written.
Writing ma_hit_ts to disk... 
ma_hit_ts has been written.
bin files have been written.
[M::hamt_clean_graph] no debug gfa
[debug::hamt_normalize_ma_hit_t_single_side_advance] nb_batch: 4
[M::hamt_normalize_ma_hit_t_single_side_advance] typeA 17 B 39, used 0.0s

[debug::hamt_normalize_ma_hit_t_single_side_advance] nb_batch: 4
[M::hamt_normalize_ma_hit_t_single_side_advance] typeA 0 B 0, used 0.0s

[M::clean_weak_ma_hit_t] treated 0, used 0.0s
[M::ma_hit_sub] remained 241, deleted 0, used 0.0s
[M::detect_chimeric_reads_conservative] n_simple_remove: 0, n_complex_remove: 0/0, used 0.0
[M::ma_hit_cut] typeA 0 , typeB 223, used 0.0
[M::ma_hit_flt] typeA 0 , typeB 223, used 0.0s
[M::hamt_hit_contained_multi] treated roughly 0 spots, used 0.0s
[M::hamt_hit_contained_drop_singleton_multi] treated roughly 0 spots, used 0.0s
[debug::ma_hit_contained_advance] ret0: 1, used 0.00 s
[M::ma_hit_contained_advance] dropped 225 reads, used total of 0.00 s

[M::asg_arc_del_trans] reduced 0 arcs, used 0.0s
[M::asg_cut_tip] cut 8 tips, used 0.0 s
[M::hamt_clean_graph] ====== initial clean ======


**********0-th round drop: drop_ratio = 0.200000**********
[M::asg_arc_del_simple_circle_untig] removed 0 self-circles, used 0.0s
[M::asg_cut_tip] cut 0 tips, used 0.0 s
[M::hamt_asgarc_drop_tips_and_bubbles] did 0 rounds, dropped 0 spots, used 0.0 s

[M::asg_arc_identify_simple_bubbles_multi] dropped total of 0, used 0.0s
[M::asg_arc_del_false_node_meta] removed 0 single nodes, used 0.0
[M::asg_cut_tip] cut 0 tips, used 0.0 s
[M::asg_arc_identify_simple_bubbles_multi] dropped total of 0, used 0.0s
[M::asg_arc_del_short_diploid_by_exact] removed 0 inexact overlaps, used 0.0s
[M::asg_cut_tip] cut 0 tips, used 0.0 s
[M::asg_arc_identify_simple_bubbles_multi] dropped total of 0, used 0.0s
[M::asg_arc_del_short_diploid_by_length] removed 0 short overlaps, used 0.0
[M::asg_cut_tip] cut 0 tips, used 0.0 s
[M::asg_arc_identify_simple_bubbles_multi] dropped total of 0, used 0.0s
[M::asg_arc_del_short_false_link] removed 0 false overlaps, used 0.0s
[M::asg_arc_identify_simple_bubbles_multi] dropped total of 0, used 0.0s
[M::asg_arc_del_complex_false_link] removed 0 false overlaps, used 0.0s
[M::asg_cut_tip] cut 0 tips, used 0.0 s


**********1-th round drop: drop_ratio = 0.400000**********
[M::asg_arc_del_simple_circle_untig] removed 0 self-circles, used 0.0s
[M::asg_cut_tip] cut 0 tips, used 0.0 s
[M::hamt_asgarc_drop_tips_and_bubbles] did 0 rounds, dropped 0 spots, used 0.0 s

[M::asg_arc_identify_simple_bubbles_multi] dropped total of 0, used 0.0s
[M::asg_arc_del_false_node_meta] removed 0 single nodes, used 0.0
[M::asg_cut_tip] cut 0 tips, used 0.0 s
[M::asg_arc_identify_simple_bubbles_multi] dropped total of 0, used 0.0s
[M::asg_arc_del_short_diploid_by_exact] removed 0 inexact overlaps, used 0.0s
[M::asg_cut_tip] cut 0 tips, used 0.0 s
[M::asg_arc_identify_simple_bubbles_multi] dropped total of 0, used 0.0s
[M::asg_arc_del_short_diploid_by_length] removed 0 short overlaps, used 0.0
[M::asg_cut_tip] cut 0 tips, used 0.0 s
[M::asg_arc_identify_simple_bubbles_multi] dropped total of 0, used 0.0s
[M::asg_arc_del_short_false_link] removed 0 false overlaps, used 0.0s
[M::asg_arc_identify_simple_bubbles_multi] dropped total of 0, used 0.0s
[M::asg_arc_del_complex_false_link] removed 0 false overlaps, used 0.0s
[M::asg_cut_tip] cut 0 tips, used 0.0 s


**********2-th round drop: drop_ratio = 0.600000**********
[M::asg_arc_del_simple_circle_untig] removed 0 self-circles, used 0.0s
[M::asg_cut_tip] cut 0 tips, used 0.0 s
[M::hamt_asgarc_drop_tips_and_bubbles] did 0 rounds, dropped 0 spots, used 0.0 s

[M::asg_arc_identify_simple_bubbles_multi] dropped total of 0, used 0.0s
[M::asg_arc_del_false_node_meta] removed 0 single nodes, used 0.0
[M::asg_cut_tip] cut 0 tips, used 0.0 s
[M::asg_arc_identify_simple_bubbles_multi] dropped total of 0, used 0.0s
[M::asg_arc_del_short_diploid_by_exact] removed 0 inexact overlaps, used 0.0s
[M::asg_cut_tip] cut 0 tips, used 0.0 s
[M::asg_arc_identify_simple_bubbles_multi] dropped total of 0, used 0.0s
[M::asg_arc_del_short_diploid_by_length] removed 0 short overlaps, used 0.0
[M::asg_cut_tip] cut 0 tips, used 0.0 s
[M::asg_arc_identify_simple_bubbles_multi] dropped total of 0, used 0.0s
[M::asg_arc_del_short_false_link] removed 0 false overlaps, used 0.0s
[M::asg_arc_identify_simple_bubbles_multi] dropped total of 0, used 0.0s
[M::asg_arc_del_complex_false_link] removed 0 false overlaps, used 0.0s
[M::asg_cut_tip] cut 0 tips, used 0.0 s


**********3-th round drop: drop_ratio = 0.800000**********
[M::asg_arc_del_simple_circle_untig] removed 0 self-circles, used 0.0s
[M::asg_cut_tip] cut 0 tips, used 0.0 s
[M::hamt_asgarc_drop_tips_and_bubbles] did 0 rounds, dropped 0 spots, used 0.0 s

[M::asg_arc_identify_simple_bubbles_multi] dropped total of 0, used 0.0s
[M::asg_arc_del_false_node_meta] removed 0 single nodes, used 0.0
[M::asg_cut_tip] cut 0 tips, used 0.0 s
[M::asg_arc_identify_simple_bubbles_multi] dropped total of 0, used 0.0s
[M::asg_arc_del_short_diploid_by_exact] removed 0 inexact overlaps, used 0.0s
[M::asg_cut_tip] cut 0 tips, used 0.0 s
[M::asg_arc_identify_simple_bubbles_multi] dropped total of 0, used 0.0s
[M::asg_arc_del_short_diploid_by_length] removed 0 short overlaps, used 0.0
[M::asg_cut_tip] cut 0 tips, used 0.0 s
[M::asg_arc_identify_simple_bubbles_multi] dropped total of 0, used 0.0s
[M::asg_arc_del_short_false_link] removed 0 false overlaps, used 0.0s
[M::asg_arc_identify_simple_bubbles_multi] dropped total of 0, used 0.0s
[M::asg_arc_del_complex_false_link] removed 0 false overlaps, used 0.0s
[M::asg_cut_tip] cut 0 tips, used 0.0 s


********** last round **********
[M::asg_arc_del_simple_circle_untig] removed 0 self-circles, used 0.0s
[M::asg_cut_tip] cut 0 tips, used 0.0 s
[M::hamt_asgarc_drop_tips_and_bubbles] did 0 rounds, dropped 0 spots, used 0.0 s

[M::asg_arc_del_short_diploi_by_suspect_edge] removed 0 suspect overlaps, used 0.0s
[M::asg_cut_tip] cut 0 tips, used 0.0 s
[M::asg_arc_del_triangular_directly] removed 0 triangular overlaps, used 0.0s
[M::asg_arc_identify_simple_bubbles_multi] dropped total of 0, used 0.0s
[M::asg_cut_tip] cut 0 tips, used 0.0 s
[M::asg_arc_identify_simple_bubbles_multi] dropped total of 0, used 0.0s
[M::asg_arc_del_too_short_overlaps] removed 0 short overlaps, used 0.0s
[M::asg_cut_tip] cut 0 tips, used 0.0 s
[M::asg_arc_del_simple_circle_untig] removed 0 self-circles, used 0.0s


********** checkpoint: r_utg **********
Writing raw unitig GFA to disk... 
[M::hamt_clean_graph] ======= preclean =======
[M::hamt_ug_pop_simpleInvertBubble] popped 0 locations
[M::hamt_ug_oneutgCircleCut] treated 0 spots
[M::hamt_clean_graph] round 0, dropped 0, used 0.0s


********** checkpoint: p_utg **********

[M::hamt_output_unitig_graph_advance] Writing GFA... 
[M::hamt_ug_drop_shorter_ovlp] cut 0
[M::hamt_asgarc_ugCovCutDFSCircle_aggressive] cut 0.


[M::hamt_clean_graph] time check #1, 0.0s
[M::hamt_ug_oneutgCircleCut] treated 0 spots
[M::hamt_ug_basic_topoclean_simple] total cut: 0
Segmentation fault (core dumped)
```

**Comment by xfengnefx** [comment]
Thank you very much for the log. I reproduced the segfault. I didn't notice I used a different command and dodged it.  Sorry, I should've checked with you before pr to conda. 

Would any tiny test input do for galaxy? I made a 903KB (70 reads, 186KB gz'd) file [tiny.fa.gz](https://github.com/xfengnefx/hifiasm-meta/files/10552973/tiny.fa.gz). It's simulated from a small region of E.coli genomes. I tested with --force-rs (t=1 and t=48), also regular run with t=1. If this sounds ok, I might want to lump the actual fix into next release or commit, as regular-sized input probably won't meet this crash. Thanks again for the example.

**Comment by TomHarrop** [comment]
Yes, an "official" test data set that size would be very helpful, and any data source is fine. I'll add it to the Galaxy tool with your next release.

I doubt anyone is using data this small in the real world, so it's good to know it won't be a problem for people running the tool on Galaxy. 

Thanks again!
